/** @type {import("@commitlint/types").UserConfig} */
export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "chore",
        "build",
        "ci",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "react",
        "styles",
        "cli",
        "registry",
        "eslint-config",
        "docs",
        "deps",
        "ci",
        "release",
        "repo",
        "button",
        "input",
        "textarea",
        "label",
        "checkbox",
        "radio-group",
        "switch",
        "select",
        "slider",
        "toggle",
        "toggle-group",
        "input-otp",
        "form",
        "card",
        "separator",
        "badge",
        "avatar",
        "aspect-ratio",
        "skeleton",
        "progress",
        "alert",
        "alert-dialog",
        "dialog",
        "drawer",
        "sheet",
        "popover",
        "tooltip",
        "hover-card",
        "dropdown-menu",
        "context-menu",
        "menubar",
        "navigation-menu",
        "tabs",
        "accordion",
        "collapsible",
        "toast",
        "scroll-area",
        "resizable-panels",
        "table",
        "data-table",
        "calendar",
        "date-picker",
        "combobox",
        "command",
        "carousel",
        "pagination",
        "breadcrumb",
        "sidebar",
        "typography",
        "provider",
        "engine",
        "tokens",
        "preset",
        "a11y",
        "rtl",
        "themes",
        "motion",
      ],
    ],
    "subject-case": [2, "never", ["pascal-case", "upper-case"]],
    "header-max-length": [2, "always", 100],
    "body-max-line-length": [2, "always", 200],
    "footer-max-line-length": [2, "always", 200],
  },
}
